### ISSUE TITLE
Failed to verify macro usage

### ISSUE THREAD

**Issue by Smellon69** [notpidgey/EagleVM#5]
[+] loaded EagleVMSandbox.exe -> 11776 bytes
[>] image sections
    name       va         size
  1 .text      4096       4096
  2 .rdata     8192       4608
  3 .data      16384      512
  4 .pdata     20480      512
  5 .rsrc      24576      512
  6 .reloc     28672      512

[>] image imports
    source               import
  1 EagleVMStub.dll      ?fnEagleVMBegin@@YAXXZ
  2 EagleVMStub.dll      ?fnEagleVMEnd@@YAXXZ

[+] porting original pe properties to new executable...
[>] image base -> 5368709120 bytes
[>] section alignment -> 4096 bytes
[>] file alignment -> 512 bytes
[>] stack reserve -> 1048576 bytes
[>] stack commit -> 4096 bytes
[>] heap reserve -> 1048576 bytes
[>] heap commit -> 4096 bytes

[>] searching for uses of vm macros...
    rva        vm
  1 4368       vm_end
  2 4404       vm_begin

[+] failed to verify macro usage

this was from me protecting the sandbox exe(also I removed some things to make the log not so long)

**Comment by notpidgey** [comment]
Hi, are you building the sandbox project on debug or release?
Currently there is a little bug with the macro usage because the order of imports can vary between debug and release.

The issue lies in this [code](https://github.com/notpidgey/EagleVM/blob/master/EagleVM/source/pe/pe_parser.cpp#L58C1-L85C12)
I intend on fixing this soon after I figure out a logic problem Im having with virtualizing basic blocks.

Try to change the build of sandbox between debug <-> release. This is not a solution, just a short term fix. Let me know if it works, and if it doesn't Ill get it changed soon.

**Comment by notpidgey** [comment]
This should resolve the issue you are having. Please let me know when you have the time.

**Comment by Smellon69** [comment]
> Did you pull the new changes?

the source is so broken for me it will take like 20 minutes to fix. I will re-fix it I guess.

**Comment by Smellon69** [comment]
@notpidgey what happened to the visual studio files? like .sln

**Comment by notpidgey** [comment]
The project now only supports CMake. If you want to use Visual Studio in a solution structure you can clone the project and use CMake to generate a Visual Studio solution.
