### ISSUE TITLE
Possible MOVSX translation error

### ISSUE THREAD

**Issue by Smellon69** [notpidgey/EagleVM#8]
If you try to print or save a string to memory in a virtualized code segment, it will produce random unicode characters with no correlation to the string.

Here's code to reproduce it:
```
std::string key;
std::cout << "license key: ";
std::cin >> key;

fnEagleVMBegin();

if (key == "1798263718265567865") {
    std::cout << "correct key";
}

if (key != "1798263718265567865") {
    std::cout << "incorrect key";
}

fnEagleVMEnd();
```

**Expected behavior**
Input: "1798263718265567865"
Output: "correct key"

Input: NOT "1798263718265567865"
Output: "incorrect key"

**Screenshots**
![image](https://github.com/notpidgey/EagleVM/assets/74884194/3e692955-c315-4fee-8fc5-f4c7b822a0ea)

**Comment by Smellon69** [comment]
Found this while debugging, seems to cause some sort of ntdll error.
![image](https://github.com/notpidgey/EagleVM/assets/74884194/9483a91e-57ec-42df-a800-bcb895365463)

**Comment by notpidgey** [comment]
The exception is not caused by NTDLL but due to some kind of incorrect instruction translation. 

I cannot be bothered to debug this manually to see which VM handler is incorrect, but my best guess would be the translation for "movzx eax, al" is not right. Currently a testing project is being worked on to make sure the intended function of x86 instructions is preserved after virtualization. This will solve the bigger problem of instructions getting incorrectly virtualized instead of me trying to figure out case by case what is wrong.

For now I don't suggest opening any issues related to crashing being caused by virtualization. I hope that some of these problems will be mitigated by what I discover from the tests. I'll tag you when I believe its fixed.

**Comment by Smellon69** [comment]
Mr. notpidgey, I have something that may help you in development. I happen to have the **entire** VMProtect 3.6.1 source code. I don't know if it could help you, but if it can, I can give it to you.

**Comment by notpidgey** [comment]
Appreciate the offer but I have already seen the source

**Comment by notpidgey** [comment]
No longer crashing after 40ba45f but producing unexpected results.

**Comment by notpidgey** [comment]
```
std::string key;
std::cout << "license key: ";
std::cin >> key;

fnEagleVMBegin();

if (key == "1798263718265567865") {
    std::cout << "correct key";
}

if (key != "1798263718265567865") {
    std::cout << "incorrect key";
}

fnEagleVMEnd();
```

Works for me now. Please confirm on your end by merging the new changes

**Comment by Smellon69** [comment]
> ```
> 
> std::string key;
> 
> std::cout << "license key: ";
> 
> std::cin >> key;
> 
> 
> 
> fnEagleVMBegin();
> 
> 
> 
> if (key == "1798263718265567865") {
> 
>     std::cout << "correct key";
> 
> }
> 
> 
> 
> if (key != "1798263718265567865") {
> 
>     std::cout << "incorrect key";
> 
> }
> 
> 
> 
> fnEagleVMEnd();
> 
> ```
> 
> 
> 
> Works for me now. Please confirm on your end by merging the new changes

I'll check it out when I have time. Thanks in advance.
